services:
  - type: web
    name: flexstore-back
    env: docker
    plan: starter
    repo: https://github.com/eolivier/flexstore
    branch: main
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /actuator/health
    envVars:
      - key: FLEXSTORE_DATABASE_URL
          fromDatabase:
            name: flexstore-db
            property: connectionString

databases:
  - name: flexstore-db
    databaseName: flexstore
    plan: free
