services:
  - type: web
    name: flexstore-back
    env: docker
    plan: starter
    repo: https://github.com/eolivier/flexstore
    branch: main
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /actuator/health
    envVars:
      - key: FLEXSTORE_DATASOURCE_HOST
        fromDatabase:
          name: flexstore-db
          property: host
      - key: FLEXSTORE_DATASOURCE_PORT
        fromDatabase:
          name: flexstore-db
          property: port
      - key: FLEXSTORE_DATASOURCE_DATABASE
        fromDatabase:
          name: flexstore-db
          property: database
      - key: FLEXSTORE_DATASOURCE_USERNAME
        fromDatabase:
          name: flexstore-db
          property: user
      - key: FLEXSTORE_DATASOURCE_PASSWORD
        fromDatabase:
          name: flexstore-db
          property: connectionString

databases:
  - name: flexstore-db
    databaseName: flexstore
    plan: free
